Homework/unit 11
minhquang55/Exercise pull request #5
Opened 2020-10-28 15:31 UTC by minhquang55

1. Thông tin cá nhân
- Họ tên: Trần Minh Quang
- Lớp: Reactjs2009
- Buổi: 10
2. Mô tả tasks (mô tả các bài tập)
https://github.com/trunghongoc/REACTJS2009E-exercises/tree/main/unit-11?fbclid=IwAR2hw35a6l4nNdD-mkPSw-Shbekzith83ollIHdMPAXV8LOd4rJPEZPOBRg
3. Các vấn đề (issues)
Em lỡ add cả thay đổi của exercise trước vào nên nó thành 2 file changed, em kb sửa như nào! 
4. Ghi chú khác
File changed của excercise 11 là file bên dưới ạ!

2020-10-28 16:47 UTC, trunghongoc requested changes
1.
Link bài tập:
Bad: https://github.com/trunghongoc/REACTJS2009E-exercises/tree/main/unit-11?fbclid=IwAR0DDmQ4pXONxHyIdpx355qWrF36PUxY9qAuIN_5lzdqRN6spblD2Bw5daI
Good: https://github.com/trunghongoc/REACTJS2009E-exercises/tree/main/unit-11

2.
![image](https://user-images.githubusercontent.com/25766981/97467300-a3ceb380-1976-11eb-9cf6-6a8bf0257b7a.png)

Không được dùng tiếng Việt

3.
Dấu cách vẫn sai rất nhiều

---> donate 20k

2020-10-28 16:47 UTC, trunghongoc commented on homework-10/script.js
> +//Bai 1 : In bang nhan
```suggestion
// Bai 1 : In bang nhan
```
Và không được dùng tiếng Việt
Có thể `quotes` lại đề bài

2020-10-28 16:47 UTC, trunghongoc commented on homework-10/script.js
> +const displayMul = n => {
`Mul` ?
`n` ?

2 cái này là cái gì?

2020-10-28 16:47 UTC, trunghongoc commented on homework-10/script.js
> +    console.log('In bang nhan:')
xóa dòng log đi

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//cach 1:
Không được dùng tiếng Việt
Chú ý dấu cách
```suggestion
// Bai 1:
// Cach 1:
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//cach 2:
```suggestion
// Cach 2:
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//Bai 2:
```suggestion
// Bai 2:
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//Bai 3:
```suggestion
// Bai 3:
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +}
Xem hàm filter ở: https://github.com/vanphongnguyen1/Reactjs2009E-exercises/pull/3

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//Bai 5: sort
```suggestion
// Bai 5: sort
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//Bai 6:
```suggestion
// Bai 6: 
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +}
`inputDate` ?? cái gì có `date` ở  đây?

thử chạy `checkTypeObject(null)`

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//Bai 8:
```suggestion
// Bai 8:
```

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +      let nameArray = element.name.split(' ');
`nameArray` bên dưới có bị thay đổi ko mà đặt `let`?

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +}
`if else` gì 1 đống thế này?

Sẽ ra sao nếu tên của 1 student chỉ đơn giản là `Duy` họ cũng là tên, cũng là tên đệm?

2020-10-28 16:47 UTC, trunghongoc commented on homework-11/script.js
> +//Bai 10:
```suggestion
// Bai 10:
```

2020-10-29 02:16 UTC, minhquang55 commented on homework-10/script.js
> +    console.log('In bang nhan:')
Em viết vào cho giống đề bài :3

2020-10-29 02:18 UTC, minhquang55 commented on homework-10/script.js
> +//Bai 1 : In bang nhan
Cái dấu cách này là từ bài 10 anh chưa chữa cho em nên em vẫn mắc nên ko tính là lỗi được đâu anh!

2020-10-29 02:30 UTC, minhquang55 commented on homework-11/script.js
> +      if (nameArray[nameArray.length-2] != 'Duy') newArray.push('Pass');
Em thấy không cần thêm 1 dấu '=' cũng được!

2020-10-29 02:32 UTC, minhquang55 commented on homework-11/script.js
> +}
thế thì đấy là tên chứ ko tính là tên đệm chứ ạ! Tên như vậy thì ko tính là tên đệm đâu anh

2020-10-29 02:35 UTC, minhquang55 commented on homework-11/script.js
> +}
ra false ạ!

2020-10-29 02:36 UTC, minhquang55 commented on homework-11/script.js
> +const exceptProps = (key1,key2) => {
người ta bắt truyền vào key sao lại là obj và arr ạ?

2020-10-29 11:42 UTC, merged